project_name: csvdiff

release:
  github:
    owner: aswinkarthik
    name: csvdiff

builds:
  - main: ./main.go
    binary: csvdiff
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    linux: linux
  homepage: https://github.com/aswinkarthik93/csvdiff
  maintainer: aswinkarthik93
  description: A Blazingly fast diff tool for comparing csv files.
  license: MIT
  formats:
    - deb
    - rpm